research_task:
  description: >
    Conduct a thorough research about the benefit's that eXp Realty offers it's Real Estate agents across the websites provided.
    
    - https://us.exprealty.com/
    - https://expworldholdings.com/press-releases/exp-realty-announces-strategic-leadership-changes-to-enhance-global-growth/
    - https://expworldholdings.com/news/

    Make sure you find any interesting and relevant information given the current date is { current_date }.
  expected_output: >
    5 Bulletpoints of the top 5 insights representing the most important information that are of importance to
    Real Estate Agents that are thinking or are already a part of the eXp Realty Platform.
    The insights should be retrieved from the various website. Include a summary of insight and include detailed sources
    and citations so that the information can be verified. Include links to the sources in the final output.