research_task:
  description: >
    Conduct thorough research about A.I. for business owners across the websites provided.
    
    - Wired.com (https://www.wired.com/)
    - Wired.com's Artifical Intelligence Page (https://www.wired.com/tag/artificial-intelligence/)
    - TechCrunch.com (https://techcrunch.com/)
    - TechCrunch.com's Artifical Intelligence Page (https://techcrunch.com/category/artificial-intelligence/)
    
    Make sure you find any interesting and relevant information given the current date is { current_date }.
  expected_output: >
    5 Bulletpoints of the top 5 insights representing the most important developments retrieved from the various news outlets.
    Include a summary of each insight and include detailed sources and citations so that the information can be verified.
    Include links to the sources in the final output. Finally, generate an idea for a practical tool to suggest to business owners and include a link
    where to find more information about the tool.