name: Build and Deploy to Cloud Run Job

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: kalygo-436411 # Google Cloud project id
  JOB_NAME: my-job # Cloud Run Job name
  JOB_REGION: us-east1 # Cloud Run region
  ARTIFACTORY_URL: us-east1-docker.pkg.dev/kalygo-436411/job-2-repo/job-2-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -f Dockerfile -t "${{ env.ARTIFACTORY_URL }}:${{ github.sha }}" ./
          docker push "${{ env.ARTIFACTORY_URL }}:${{ github.sha }}"

      - name: Deploy to Cloud Run Jobs
        run: |
          gcloud run jobs execute $JOB_NAME --region $JOB_REGION --project $YOUR_PROJECT_ID
